modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/CERBON-MODS/Sugared-Concrete-Powder-FORGE/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://www.curseforge.com/minecraft/mc-mods/sugared-concrete-powder"
logoFile="logo.png"
#credits="Thanks for this example mod goes to Java"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
   modId="forge"
   mandatory=true
   versionRange="${forge_version_range}"
   ordering="NONE"
   side="BOTH"

[[dependencies.${mod_id}]]
   modId="minecraft"
   mandatory=true
   versionRange="${minecraft_version_range}"
   ordering="NONE"
   side="BOTH"

[[dependencies.${mod_id}]]
   modId="cerbons_api"
   mandatory=true
   versionRange="${cerbons_api_version_range}"
   ordering="NONE"
   side="BOTH"